version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: "API/Dockerfile"
    ports:
      - "5001:5001"
    depends_on:
      - redis
      - seq
    environment:
      - "AppSettings__ConnectionStrings__SQLite=Data Source=../DB/dev"
      - "AppSettings__ConnectionStrings__Redis=redis:6379"
      - SEQ_URL=http://seq:5341
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - cdn-redis:/data
    networks:
      - backend

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - cdn-seq:/data
    networks:
      - backend

volumes:
  cdn-redis:
  cdn-seq:

networks:
  backend:
    driver: bridge